### ISSUE TITLE
Modul ovlivňuje ostatní přepravy při dokončení objednávky

### ISSUE THREAD

**Issue by ulozenka** [ulozenka/prestashop-1-4#3]
V sekci Moduly pro e-shopová řešení jsem si stáhl modul pro Prestashop 1.4.9 (verze 1.2.b). Nainstaloval jsem jej na e-shop běžící na Prestashopu 1.4.9.

Spustila se vlna stížností ze strany zákazníků e-shopu. Tento modul způsobuje jednu zásadní chybu. Pokud si zákazník vybere jinou formu dopravy mimo Uloženku, vyhazuje to chybové hlášení "Please select store" a objednávka nejde dokončit. Jediná možnost jak tuto chybu obejít je, že
se musí vybrat jakákoliv pobočka ve výběru Uloženky a potom už jde použít jiného přepravce. Kvůli této chybě je modul nepoužitelný. Zákazníci nepřichází na to, že to jde oklikou a ti lepší si stěžují. Ti
co si nestěžují nedokončí objednávku.

Zkoušel jsem to v prohlížeči, který má nastaveno neukládat cache. Tzn. že po každém spuštění je čistý. Zde to dělá tu chybu. Pokud je nasteno ukládání cache, tak se po prvním nastavení pobožky chyba znovu neopakuje. Tzn. že každý prvo zákazník má tento problém. Což je skoro každý.

Nemáte prosím nějaké řešení tohoto problému?

**Comment by ulozenka** [comment]
Dobrý den,

můžete prosím vyzkoušet aktuální verzi modulu, zda se v ní popisovaná chyba vyskytuje?

Odkaz na stažení:
https://github.com/ulozenka/prestashop-1-4/releases/download/1.3b/ulozenka13b.zip

**Comment by prestahost** [comment]
chyba se týkala objednávky v 5 krocích a v 1.3b by měla být opravena
